# Read csv file

In [1]:
import pandas as pd
iris=pd.read_csv('iris.csv')
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

# Show column head  '10 data'

In [2]:
print(iris.head(10))
# or use 
# print(iris.iloc[0:10])

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

# Show all column

In [3]:
print(iris.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

# Show all data each column

In [4]:
print(iris["Species"])
# or use 
# print(iris.Species)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [5]:
print(iris.iterrows)

<bound method DataFrame.iterrows of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

# Craete table

In [6]:
display(iris)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# Create table have checking

In [8]:
iris.loc[iris['Species'] == 'Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

# Describing Data

In [9]:
for Id, Species in iris.iterrows():
    print(Id,":", Species["Species"])

0 : Iris-setosa
1 : Iris-setosa
2 : Iris-setosa
3 : Iris-setosa
4 : Iris-setosa
5 : Iris-setosa
6 : Iris-setosa
7 : Iris-setosa
8 : Iris-setosa
9 : Iris-setosa
10 : Iris-setosa
11 : Iris-setosa
12 : Iris-setosa
13 : Iris-setosa
14 : Iris-setosa
15 : Iris-setosa
16 : Iris-setosa
17 : Iris-setosa
18 : Iris-setosa
19 : Iris-setosa
20 : Iris-setosa
21 : Iris-setosa
22 : Iris-setosa
23 : Iris-setosa
24 : Iris-setosa
25 : Iris-setosa
26 : Iris-setosa
27 : Iris-setosa
28 : Iris-setosa
29 : Iris-setosa
30 : Iris-setosa
31 : Iris-setosa
32 : Iris-setosa
33 : Iris-setosa
34 : Iris-setosa
35 : Iris-setosa
36 : Iris-setosa
37 : Iris-setosa
38 : Iris-setosa
39 : Iris-setosa
40 : Iris-setosa
41 : Iris-setosa
42 : Iris-setosa
43 : Iris-setosa
44 : Iris-setosa
45 : Iris-setosa
46 : Iris-setosa
47 : Iris-setosa
48 : Iris-setosa
49 : Iris-setosa
50 : Iris-versicolor
51 : Iris-versicolor
52 : Iris-versicolor
53 : Iris-versicolor
54 : Iris-versicolor
55 : Iris-versicolor
56 : Iris-versicolor
57 : Iris-versicolor
58 : Iris-versicolor
59 : Iris-versicolor
60 : Iris-versicolor
61 : Iris-versicolor
62 : Iris-versicolor
63 : Iris-versicolor
64 : Iris-versicolor
65 : Iris-versicolor
66 : Iris-versicolor
67 : Iris-versicolor
68 : Iris-versicolor
69 : Iris-versicolor
70 : Iris-versicolor
71 : Iris-versicolor
72 : Iris-versicolor
73 : Iris-versicolor
74 : Iris-versicolor
75 : Iris-versicolor
76 : Iris-versicolor
77 : Iris-versicolor
78 : Iris-versicolor
79 : Iris-versicolor
80 : Iris-versicolor
81 : Iris-versicolor
82 : Iris-versicolor
83 : Iris-versicolor
84 : Iris-versicolor
85 : Iris-versicolor
86 : Iris-versicolor
87 : Iris-versicolor
88 : Iris-versicolor
89 : Iris-versicolor
90 : Iris-versicolor
91 : Iris-versicolor
92 : Iris-versicolor
93 : Iris-versicolor
94 : Iris-versicolor
95 : Iris-versicolor
96 : Iris-versicolor
97 : Iris-versicolor
98 : Iris-versicolor
99 : Iris-versicolor
100 : Iris-virginica
101 : Iris-virginica
102 : Iris-virginica
103 : Iris-virginica
104 : Iris-virginica
105 : Iris-virginica
106 : Iris-virginica
107 : Iris-virginica
108 : Iris-virginica
109 : Iris-virginica
110 : Iris-virginica
111 : Iris-virginica
112 : Iris-virginica
113 : Iris-virginica
114 : Iris-virginica
115 : Iris-virginica
116 : Iris-virginica
117 : Iris-virginica
118 : Iris-virginica
119 : Iris-virginica
120 : Iris-virginica
121 : Iris-virginica
122 : Iris-virginica
123 : Iris-virginica
124 : Iris-virginica
125 : Iris-virginica
126 : Iris-virginica
127 : Iris-virginica
128 : Iris-virginica
129 : Iris-virginica
130 : Iris-virginica
131 : Iris-virginica
132 : Iris-virginica
133 : Iris-virginica
134 : Iris-virginica
135 : Iris-virginica
136 : Iris-virginica
137 : Iris-virginica
138 : Iris-virginica
139 : Iris-virginica
140 : Iris-virginica
141 : Iris-virginica
142 : Iris-virginica
143 : Iris-virginica
144 : Iris-virginica
145 : Iris-virginica
146 : Iris-virginica
147 : Iris-virginica
148 : Iris-virginica
149 : Iris-virginica

# Sorting Data

In [10]:
iris.sort_values('SepalLengthCm')
# iris.sort_values(['Id','SepalLengthCm'], ascending=[0,1])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

# Adding a column

In [11]:
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [12]:
iris['testAddColumn']=0
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species  testAddColumn
0       Iris-setosa              0
1       Iris-setosa              0
2       Iris-setosa              0
3       Iris-setosa              0
4       Iris-setosa              0
..              ...            ...
145  Iris-virginica              0
146  Iris-virginica              0
147  Iris-virginica              0
148  Iris-virginica              0
149  Iris-virginica              0

[150 rows x 7 columns]

# Deleting a column

In [13]:
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species  testAddColumn
0       Iris-setosa              0
1       Iris-setosa              0
2       Iris-setosa              0
3       Iris-setosa              0
4       Iris-setosa              0
..              ...            ...
145  Iris-virginica              0
146  Iris-virginica              0
147  Iris-virginica              0
148  Iris-virginica              0
149  Iris-virginica              0

[150 rows x 7 columns]

In [14]:
iris=iris.drop(columns=['testAddColumn'])
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

# Summing muitiplei columns to create new column

In [15]:
iris['totalColumns']=iris.iloc[:, 1:5].sum(axis=1)
print(iris)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species  totalColumns
0       Iris-setosa          10.2
1       Iris-setosa           9.5
2       Iris-setosa           9.4
3       Iris-setosa           9.4
4       Iris-setosa          10.2
..              ...           ...
145  Iris-virginica          17.2
146  Iris-virginica          15.7
147  Iris-virginica          16.7
148  Iris-virginica          17.3
149  Iris-virginica          15.8

[150 rows x 7 columns]

In [16]:
iris=iris.drop(columns=['totalColumns'])

# Rearranging columns

In [17]:
cols = list(iris.columns)
print(cols)
iris=iris[cols[0:1] + [cols[-1]] + cols[1:5]]
print(iris)

['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']
      Id         Species  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
0      1     Iris-setosa            5.1           3.5            1.4
1      2     Iris-setosa            4.9           3.0            1.4
2      3     Iris-setosa            4.7           3.2            1.3
3      4     Iris-setosa            4.6           3.1            1.5
4      5     Iris-setosa            5.0           3.6            1.4
..   ...             ...            ...           ...            ...
145  146  Iris-virginica            6.7           3.0            5.2
146  147  Iris-virginica            6.3           2.5            5.0
147  148  Iris-virginica            6.5           3.0            5.2
148  149  Iris-virginica            6.2           3.4            5.4
149  150  Iris-virginica            5.9           3.0            5.1

     PetalWidthCm
0             0.2
1             0.2
2             0.2
3             0.2
4             0.2
..            ...
145           2.3
146           1.9
147           2.0
148           2.3
149           1.8

[150 rows x 6 columns]

In [18]:
iris=pd.read_csv('iris.csv')

# Create file csv

In [19]:
iris.to_csv('testCreateFile.csv', index=False)
iris.to_excel('testCreateFile.xlsx', index=False)
iris.to_csv('testCreateFile.txt', index=False, sep='\t')

# Filtering Data

In [20]:
newiris=iris.loc[iris.SepalWidthCm == 4.1]
print(newiris)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
32  33            5.2           4.1            1.5           0.1  Iris-setosa

reset index 'newiris'

In [21]:
newiris = newiris.reset_index(drop=True)
print(newiris)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  33            5.2           4.1            1.5           0.1  Iris-setosa